### ISSUE TITLE
[Backward Compatibility Break in 0.38] `BytesText::unescape()` Removal Breaks xmltodict Compatibility

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tafia/quick-xml#889]
## Summary

The removal of `BytesText::unescape()` method in quick-xml 0.38.1 and changes to automatic unescaping behavior have broken backward compatibility for applications that need to match `xmltodict`'s text handling behavior.

## Environment

- **quick-xml version that worked**: 0.37.5
- **quick-xml version with issue**: 0.38.0
- **Rust version**: 1.x
- **Use case**: Parsing XML to match Python's `xmltodict` library behavior exactly

### Code Example

```rust
use quick_xml::{Reader, events::Event};

fn parse_xml_like_xmltodict(xml: &str) -> String {
    let mut reader = Reader::from_str(xml);
    let mut buf = Vec::new();
    
    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Text(e)) => {
                // This worked in 0.37.5
                let text = e.unescape().unwrap_or_default().to_string();
                return text;
            }
            Ok(Event::Eof) => break,
            _ => {}
        }
        buf.clear();
    }
    String::new()
}

// Test with escaped XML content
let xml = r#"<TopLevel>&lt;NestedA&gt;Object1&lt;/NestedA&gt;&lt;NestedB&gt;Object2&lt;/NestedB&gt;</TopLevel>"#;
let result = parse_xml_like_xmltodict(xml);
```

### Expected Result (and what we got in 0.37.5)

```
"<NestedA>Object1</NestedA><NestedB>Object2</NestedB>"
```

This matches exactly what Python's `xmltodict.parse()` produces for the same XML.

### Compilation Error

```rust
error[E0599]: no method named `unescape` found for struct `BytesText<'_>` in the current scope
  --> src/lib.rs:XX:XX
   |
XX |                 let text = e.unescape().unwrap_or_default().to_string();
   |                              ^^^^^^^^^ method not found in `BytesText<'_>`
```

### Attempted Workaround and Its Problems

When trying to use the new API:

```rust
use quick_xml::escape;

// Attempted fix
let raw_text = std::str::from_utf8(e.as_ref()).unwrap_or("");
let text = escape::unescape(raw_text)
    .map(|cow| cow.into_owned())
    .unwrap_or_else(|_| raw_text.to_string());
```

### Actual Result with 0.38.0

The parser now automatically unescapes during parsing and generates **multiple separate text events**:

1. `"NestedA"` 
2. `"Object1"`
3. `"/NestedA"`
4. `"NestedB"`
5. `"Object2"`
6. `"/NestedB"`

This results in only the **last** text event being captured: `"/NestedB"`

Instead of the expected: `"<NestedA>Object1</NestedA><NestedB>Object2</NestedB>"`

## Real-World Impact

This breaks any application that needs to:

1. **Match xmltodict behavior exactly** - Critical for data interchange between Python and Rust systems
2. **Preserve escaped XML content as raw strings** - Many XML files contain escaped XML fragments that should be treated as text data, not parsed as XML
3. **Maintain round-trip fidelity** - Parse XML → Process → Generate same XML

## Minimal Reproduction Case

```rust
// Cargo.toml
[dependencies]
quick-xml = "0.38.1"

// main.rs
use quick_xml::{Reader, events::Event};

fn main() {
    let xml = r#"<TopLevel>&lt;NestedA&gt;Object1&lt;/NestedA&gt;&lt;NestedB&gt;Object2&lt;/NestedB&gt;</TopLevel>"#;
    let mut reader = Reader::from_str(xml);
    let mut buf = Vec::new();
    
    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Text(e)) => {
                let text = std::str::from_utf8(e.as_ref()).unwrap();
                println!("Text event: {:?}", text);
            }
            Ok(Event::Eof) => break,
            _ => {}
        }
        buf.clear();
    }
}
```

**Output in 0.37.5**: Single text event with `"<NestedA>Object1</NestedA><NestedB>Object2</NestedB>"`
**Output in 0.38.1**: Multiple events: `"NestedA"`, `"Object1"`, `"/NestedA"`, `"NestedB"`, `"Object2"`, `"/NestedB"`

---------------------------

Thanks for the time and the help 👍

**Comment by Mingun** [comment]
You does not need `unescape`, because since 0.38.0 `BytesText` does not contains escaped text (general references `&...;`). General references are reported as new event `Event::GeneralRef`. You should process them and build text.

Please, read [release notes](https://github.com/tafia/quick-xml/releases/tag/v0.38.0) and not only rely on AI.

**Comment by jmcnamara** [comment]
> You should process them and build text.

Do you have any guidance on how to do this for standard XML entities and also `&#xN;`?

 I'm asking because we are currently trying to figure out the best way to upgrade from quick-xml v0.37 to v0.38: https://github.com/tafia/calamine/pull/557

**Comment by jmcnamara** [comment]
@Mingun And just so it doesn't seem like I'm asking you to do my homework, this is what I have so far: https://github.com/tafia/calamine/pull/561

**Comment by Mingun** [comment]
@jmcnamara , I'm reviewed your PR and it seems correct.
