### ISSUE TITLE
String recursion error after upgrading from 0.26.0 to 0.27.1

### ISSUE THREAD

**Issue by JenChampagne** [tafia/quick-xml#540]
I'm getting a really weird error after upgrading from 0.26.0 to 0.27.1. I've tried to put together a reproduce case, but I'm having difficulty doing so, but I'll give as many details as I can.

The error I get is as follows:

```
error[E0275]: overflow evaluating the requirement `&mut std::string::String: std::fmt::Write`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`lib`)
  = note: required for `&mut &mut std::string::String` to implement `std::fmt::Write`
  = note: 127 redundant requirements hidden
  = note: required for `&mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut std::string::String` to implement `std::fmt::Write`
  = note: required for `se::element::ElementSerializer<'_, &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut std::string::String>` to implement `serde::Serializer`

For more information about this error, try `rustc --explain E0275`.
error: could not compile `project` due to previous error
```

I make use of `AsRef<T>` and `Cow<'_, str>` in several cases, but I'm not sure that it is the core of the issue since I'm not able to make a reproduce case. I don't understand where the recursion of `&mut` is coming from. Nothing in my code is explicitly recursive as far as I am aware, and `cargo expand` does not highlight anything that stands out.

Does the above provide any clues that might point me in the direction of where to look in my code? I will try to again to reproduce, but the repository having the issue is a private one.

**Comment by Mingun** [comment]
This is something about serializer. [Serializer](https://docs.rs/quick-xml/latest/quick_xml/se/struct.Serializer.html) was rewritten in 0.27.0 and now writes to `fmt::Write` instead of `io::Write`. My speculation: probably you try to serialize to a string and there somewhere the unnecessary `&mut`.

**Comment by Clazex** [comment]
Met similar problem in both 0.27.0 & 0.27.1, no problem with 0.26.0

Build log with `-Z macro-backtrace`:
```
error: reached the recursion limit while instantiating `some_type::_::_serde::ser::impls::<impl Serialize for &some_type::_::_serde::__private::ser::content::Content>::serialize::<se::element::ElementSerializer<'_, &mut &mut ...>>`
   --> <REDACTED>\quick-xml-0.27.1\src\se\element.rs:211:9
    |
211 | /         value.serialize(ElementSerializer {
212 | |             ser: self.ser.new_seq_element_serializer(),
213 | |             key: self.key,
214 | |         })?;
    | |__________^
    |
note: `some_type::_::_serde::ser::impls::<impl Serialize for &'a T>::serialize` defined here
   --> <REDACTED>\serde-1.0.152\src\ser\impls.rs:423:13
    |
415 | /  macro_rules! deref_impl {
416 | |      (
417 | |          $(#[doc = $doc:tt])*
418 | |          <$($desc:tt)+
...   |
423 | |/             fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
424 | ||             where
425 | ||                 S: Serializer,
    | ||______________________________^
...   |
430 | |      };
431 | |  }
    | |__- in this expansion of `deref_impl!`
432 |
433 |    deref_impl!(<'a, T: ?Sized> Serialize for &'a T where T: Serialize);
    |    ------------------------------------------------------------------- in this macro invocation
    = note: the full type name has been written to '<REDACTED>.long-type.txt'
```

`long-type.txt`:
```
some_type::_::_serde::ser::impls::<impl Serialize for &some_type::_::_serde::__private::ser::content::Content>::serialize::<se::element::ElementSerializer<'_, &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut &mut std::string::String>>
```

There is no `&mut` in all types in the crate.

**Comment by Mingun** [comment]
Could you provide the minimal reproducible example of this?

**Comment by Clazex** [comment]
[here](https://github.com/Clazex/hk_modlinks/tree/fa82b89)

**Comment by Mingun** [comment]
I shortened the example to:
```rust
use serde::Serialize;

#[derive(Serialize)]
pub enum Enum {
    Variant {},
}

#[derive(Serialize)]
pub struct Struct {
    #[serde(flatten)]
    flatten: Enum,
}

pub fn to_xml(data: &Struct) -> Result<String, quick_xml::DeError> {
    quick_xml::se::to_string(&data)
}
```
Interesting, that removing `pub` from `to_xml` fixes the problem, so probably this is a bug in `rustc`

**Comment by Clazex** [comment]
I guess `&mut` come from [here](https://github.com/tafia/quick-xml/blob/v0.27.1/src/se/element.rs#L353) because if I do `quick_xml::se::Serializer::new(std::ffi::OsString::new())`, the long-type still ends with `String`

**Comment by Clazex** [comment]
I guess `&mut` come from [here](https://github.com/tafia/quick-xml/blob/v0.27.1/src/se/element.rs#L353) because if I do `quick_xml::se::Serializer::new(std::ffi::OsString::new())`, the long-type still ends with `String`

**Comment by Clazex** [comment]
Update: This panics for `Unsupported("cannot serialize map without defined root tag")`
```rust
fn main() {
    use serde::ser::Serializer;
    quick_xml::se::Serializer::new(String::new())
        .serialize_map(None).unwrap();
}
```
However the derived `Serialize` impl for both flattened enum and flattened struct starts with `serialize_map`
So the new serializer cannot deal with flattening at all 😢

**Comment by Mingun** [comment]
> So the new serializer cannot deal with flattening at all cry

No, it is because it was created with [`new`](https://docs.rs/quick-xml/latest/quick_xml/se/struct.Serializer.html#method.new) instead of [`with_root`](https://docs.rs/quick-xml/latest/quick_xml/se/struct.Serializer.html#method.with_root). Probably I should include correct method to the error message. But you're right, flattening works poorly for XML, it is better to avoid it, especially for deserialization. In many cases it will not work due to its design.
